inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance


Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

RSpec/NestedGroups:
  Max: 4

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/**'

Rails/FilePath:
  Exclude:
    - 'spec/**'
    - 'config/**/**'

RSpec/MultipleExpectations:
  Max: 3

# using let! in my opinion makes the code more readable especially
# in system tests.
RSpec/LetSetup:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/**'
